<?php


error_reporting(E_ALL); 
ini_set("display_errors", 1); 

require_once('lib/sandhog.php');

$sandhog = new Sandhog();

$train = $sandhog->service->status('1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('2');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('3');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('4');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('5');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('6');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('7');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('a');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('c');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('e');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('b');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('d');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('f');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('m');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('g');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('l');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('n');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('q');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('r');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('s');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('sir');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('b1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('b83');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('b100');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('b103');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('bm1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('bm5');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('bx1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('bx55');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('bxm1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('bxm18');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('m1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('m116');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('n1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('n88');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('q1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('q113');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('qm1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('qm25');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('s40');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('s98');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('x1');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('x68');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('throgs neck');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('henry hudson');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('marine parkway');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('bronx-whitestone');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('brooklyn-battery');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('queens midtown');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('robert f. kennedy');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('cross bay');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('verrazano-narrows');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('city terminal zone');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('babylon');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('far rockaway');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('hempstead');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('long beach');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('montauk');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('oyster bay');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('port jefferson');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('port washington');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('ronkonkoma');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('west hempstead');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('hudson');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('harlem');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('wasaic');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('new haven');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('new canaan');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('danbury');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('waterbury');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('pascack valley');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
$train = $sandhog->service->status('port jarvis');
echo $train->name;
echo ": ";
echo $train->status;
echo "<br>";
